# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  input:          GFM

# Permalinks
permalink:        pretty

# Setup
title:            Foundations of Microeconomics
description:      'An introduction to markets, behavior, and policy.'
url:              http://potterzot.com/econs101
baseurl:          /econs101
email:            nicholas.a.potter@wsu.edu
feedbackurl:      https://goo.gl/forms/8SiOwdi19kN8cINJ3
author:
  name:           'Nicholas Potter'
  url:            https://twitter.com/potterzot

github:
  repo:           https://github.com/potterzot/econs101
  #               Be sure the 'Issues' feature is activated in 'Settings'

exclude:          ["*.Rmd"]

theme: jekyll-theme-minimal
