---
layout: page
element: lecture
title: Elasticity
date: August 22, 2018
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
library(xkcd)
library(tidyr)
library(dplyr)
library(here)
```

## Pregame

* Second quiz reschedule?
* Econ club study groups

## Feedback

<h3 style="color: green;">Good: </h3>
* Doing practice problems in class is super helpful
* Going over graphs

<h3 style="color: red;">Needs improvement: </h3>
* Allow endless attempts on homework but decrease points for each try


## Elasticities { .smaller }

* __Elasticity__ - _A percent change in response to the percent change of something else._
* __Price elasticity of demand__ - _The percent change in demand for a percent change in price._
* __Price elasticity of supply__ - _The percent change in demand for a percent change in supply._
* __Income elasticity of demand__ - _The percent change in income for a percent change in price._

Price elasticity of demand:

$$E_{p,D} = \frac{\Delta Q}{\Delta P} \frac{P}{Q}$$

## Relative Elasticity

If the elasticity is __less__ than one, the variable is __inelastic__. For example, a price elasticity of demand equal to 0.5 means that a 1% change in price only leads to a 0.5% change in quantity demanded.

If the elasticity is __greater__ than one, the variable is __elastic__. For example, a price elasticity of demand equal to 10 means that a 1% change in price leads to a 10% change in quantity demanded.

Basically, the __steeper__ a curve, the more __inelastic__ it is. The __flatter__ a curve, the more __elastic__ it is.



## Wrapping Up

* No knowledge check today!

* Please provide [feedback](https://goo.gl/forms/8SiOwdi19kN8cINJ3) on today's lecture.
