---
layout: page
element: lecture
title: Game Theory 2
date: September 10, 2018
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
library(xkcd)
library(tidyr)
library(dplyr)
library(pander)
library(here)
library(ggplot2)
```

## Feedback

<h3 style="color: green;">Good: </h3>


<h3 style="color: red;">Needs improvement: </h3>



## Example of plotting { .flexbox .vcenter }

```{r production, out.width = "100%"}
d1 <- data.frame(t = 0:16)
d1$hw1 <- 40 + log(d1$t+1)/max(log(d1$t)) * 55
d1$hw2 <- 20 + log(d1$t+1, base = exp(2))/max(log(d1$t), base = exp(2)) * 400

x1 <- 2
x2 <- x1 + 1
x3 <- 13
x4 <- x3 + 1

ggplot(data = d1) + 
  #xkcdline(data = d, aes(x = min(d$x), xend = max(d$x), y = min(d$y), yend = max(d$y)), color = "red", size = 2) + 
  geom_line(aes(x = t, y = hw1), color = "red", size = 1, alpha = .8) +
  xkcdaxis(c(0,16), c(0,100)) + 
  geom_segment(aes(x = x1, xend = x1, y = 0, yend = d1[d1$t == x1,]$hw1), color = "deepskyblue4", linetype = 2, alpha = .9) +
  geom_segment(aes(x = 0, xend = x1, y = d1[d1$t == x1,]$hw1, yend = d1[d1$t == x1,]$hw1), color = "deepskyblue4", linetype = 2, alpha = .9) +
  geom_segment(aes(x = x2, xend = x2, y = 0, yend = d1[d1$t == x2,]$hw1), color = "deepskyblue4", linetype = 2, alpha = .9) +
  geom_segment(aes(x = 0, xend = x2, y = d1[d1$t == x2,]$hw1, yend = d1[d1$t == x2,]$hw1), color = "deepskyblue4", linetype = 2, alpha = .9) +
  geom_segment(aes(x = x3, xend = x3, y = 0, yend = d1[d1$t == x3,]$hw1), color = "seagreen2", linetype = 2, alpha = .9) +
  geom_segment(aes(x = 0, xend = x3, y = d1[d1$t == x3,]$hw1, yend = d1[d1$t == x3,]$hw1), color = "seagreen2", linetype = 2, alpha = .9) +
  geom_segment(aes(x = x4, xend = x4, y = 0, yend = d1[d1$t == x4,]$hw1), color = "seagreen2", linetype = 2, alpha = .9) +
  geom_segment(aes(x = 0, xend = x4, y = d1[d1$t == x4,]$hw1, yend = d1[d1$t == x4,]$hw1), color = "seagreen2", linetype = 2, alpha = .9) +
  #xkcdline(data = d1, aes(x = 5, xend = 5, y = 0, yend = d1[d1$t == 5,]$hw1), linetype = 2) +
  xlab("Hours Running") + ylab("Final Rank") +
  theme(text = element_text(size = 16, family = "Humor Sans"))
```


## Linking an Image

[Figure 3.5 from The Economy](https://core-econ.org/the-economy/book/text/03.html#figure-3-5a)



## WSU: An example

WSU Tuition: \$5,134

Cost of classes:

| Classes | Total Cost | Marginal Cost | Average Cost | 
| ------- | ----------:| -------------:| ------------:|
| 1       | 1000       | 1000          | 1000         |
| 2       | 1750       | 750           | 875          |
| 3       | 2350       | ???           | 783.3        |
| 4       | ????       | 250           | ???          |
| 5       | 2850       | 250           | 570          |


## Wrapping Up

* Complete the [knowledge check](https://goo.gl/forms/N6XEMxRJbahxjtMA2) for today's participation point.

* Please provide [feedback](https://goo.gl/forms/8SiOwdi19kN8cINJ3) on today's lecture.
