---
title: "Trade War"
author: "Nicholas A Potter"
date: "October 22, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
---
title: 'Writing Assignment 3: Analysis of economic impacts of steel tariffs'
output: pdf_document
---

**DUE**: Wednesday, November 7th, 2018 by 5pm Pacific Time via NETTUTOR.

_Essays are submitted to a plagarism aglorithm to check for copying. Make sure you submit your own work. Plagarism is a failing offense._



*I am __not__ asking you to argue one way or the other whether the policy was good. Instead, focus on the impacts on choice themselves and write as objectively as possible.*

## Grading Rubric
Your essay should not exceed one typed page with one-inch margins and 12-point font single spaced.  Please include your name, instructor’s name (Potter), course and section number 1 (i.e. EconS 101.01), and writing assignment (assignment 1) on the top of your assignment in 12-point font. Your essay will be assessed as either “Meets Expectations” or “Needs Improvement” on both the writing portion and economic analysis. If your essay needs improvement, you will be given feedback from NetTutor to help you revise it.  You can then re-submit the essay to NetTutor for another try, but you only get one second chance. If you take materials or quotes from sources, you must provide citations/references in a standard citation/reference format. The references do not count toward the one page limit. Here are the criteria your essay will be judged against:

| Criterion | Needs Improvement | Meets Expectations |
| --------- | ----------------- | ------------------ |
| Writing   | The writing is difficult to follow and/or poorly organized.  Transition sentences are absent or ineffective.  Typos and/or grammatical errors distract the reader. Source material citations/references needed, but are missing or incorrect. | Ideas are well-organized.  Transition sentences effectively connect one idea to the next.  The essay is free of typos and grammatical errors. Sources properly cited and referenced, any citation style is acceptable. |
| Application of economic analysis | Does not provide correct interpretation of how the change in price would affect the choice between SSBs and water. Fails to discuss the impact on utility correctly. Does not identify the primary issue with Berkeley being a small city attempting to implement this tax. | Correctly identifies the answers to parts a, b, and c above and provides correct justification for answers. |

